from pathlib import Path
import subprocess
import sys
import time


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_PATH = PROJECT_ROOT / "data" / "production_quality_data.csv"

PIPELINE_STEPS = [
    {
        "name": "Validate production dataset",
        "script": PROJECT_ROOT / "src" / "validate_data.py",
    },
    {
        "name": "Train scrap prediction model",
        "script": PROJECT_ROOT / "src" / "train_model.py",
    },
    {
        "name": "Compare classification models",
        "script": PROJECT_ROOT / "src" / "compare_models.py",
    },
    {
        "name": "Tune classification threshold",
        "script": PROJECT_ROOT / "src" / "tune_threshold.py",
    },
    {
        "name": "Optimize threshold by operational cost",
        "script": PROJECT_ROOT / "src" / "optimize_threshold_cost.py",
    },
    {
        "name": "Review new production batch",
        "script": PROJECT_ROOT / "src" / "review_batch.py",
    },
    {
        "name": "Export dashboard data",
        "script": PROJECT_ROOT / "src" / "export_dashboard_data.py",
    },
    {
        "name": "Generate quality analysis report",
        "script": PROJECT_ROOT / "src" / "analyze_quality.py",
    },
]

def check_required_files() -> None:
    """Check whether the required input dataset exists."""
    if not DATA_PATH.exists():
        raise FileNotFoundError(
            f"Dataset not found at {DATA_PATH}\n"
            "Please run `python src/generate_data.py` first or place your own dataset at "
            "`data/production_quality_data.csv`."
        )


def run_step(step_name: str, script_path: Path) -> None:
    """Run one pipeline step as a subprocess."""
    print("\n" + "=" * 72)
    print(f"Running step: {step_name}")
    print(f"Script: {script_path.relative_to(PROJECT_ROOT)}")
    print("=" * 72)

    start_time = time.time()

    result = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=PROJECT_ROOT,
        text=True,
    )

    duration = time.time() - start_time

    if result.returncode != 0:
        raise RuntimeError(
            f"Pipeline step failed: {step_name}\n"
            f"Script: {script_path}\n"
            f"Exit code: {result.returncode}"
        )

    print(f"Completed step: {step_name} ({duration:.1f}s)")


def print_output_summary() -> None:
    """Print the files generated by the pipeline."""
    outputs = [
        PROJECT_ROOT / "outputs" / "data_quality_report.json",
        PROJECT_ROOT / "outputs" / "data_quality_report.md",
        PROJECT_ROOT / "outputs" / "model_metrics.json",
        PROJECT_ROOT / "outputs" / "model_comparison.csv",
        PROJECT_ROOT / "outputs" / "best_model_summary.json",
        PROJECT_ROOT / "outputs" / "feature_importance.csv",
        PROJECT_ROOT / "outputs" / "scrap_prediction_model.joblib",
        PROJECT_ROOT / "outputs" / "threshold_metrics.csv",
        PROJECT_ROOT / "outputs" / "selected_threshold.json",
        PROJECT_ROOT / "outputs" / "threshold_cost_analysis.csv",
        PROJECT_ROOT / "outputs" / "cost_optimized_threshold.json",
        PROJECT_ROOT / "outputs" / "batch_review_results.csv",
        PROJECT_ROOT / "outputs" / "batch_review_summary.json",
        PROJECT_ROOT / "outputs" / "batch_review_report.md",
        PROJECT_ROOT / "outputs" / "prediction_results.csv",
        PROJECT_ROOT / "dashboard" / "dashboard_data.json",
        PROJECT_ROOT / "outputs" / "quality_report.md",
    ]

    print("\n" + "=" * 72)
    print("Pipeline completed successfully.")
    print("Generated / updated files:")
    print("=" * 72)

    for path in outputs:
        status = "OK" if path.exists() else "MISSING"
        print(f"[{status}] {path.relative_to(PROJECT_ROOT)}")


def main() -> None:
    print("AI Production Quality Analyzer Pipeline")
    print("=" * 72)

    check_required_files()

    for step in PIPELINE_STEPS:
        run_step(step_name=step["name"], script_path=step["script"])

    print_output_summary()


if __name__ == "__main__":
    main()
